262 books buyback hardcoded endpoints
ECE-458-Books/ece458books pull request #275
Opened 2023-02-17 06:18 UTC by danielfeinblatt

## Feature Description/Implementation
Implement hardcoded dumb endpoint for books buyback GET detail info, POST to create a new buyback, DELETE to delete a buyback, and updates.
## Dependencies
Will allow frontend to integrate as they code, rather than waiting.
## Everything Else
Need to clarify structure of the update request

2023-02-18 17:02 UTC, caseyszilagyi requested changes
One more thing: does this include the buyback list endpoint (GET /api/v1/buybacks for displaying on the buyback list page)? Or is that more difficult to hardcode?

2023-02-19 00:43 UTC, danielfeinblatt commented on backend/buybacks/views.py
> +    def update(self, request, *args, **kwargs):
Okay, so you don't need anything returned? Just a confirmation it succeeded?

2023-02-19 00:46 UTC, danielfeinblatt commented
> One more thing: does this include the buyback list endpoint (GET /api/v1/buybacks for displaying on the buyback list page)? Or is that more difficult to hardcode?

That is hardcoded under the `retrieve` method in the `RetrieveUpdateDestroyBuybackAPIView`. Let me know if this is not what you are looking for.

2023-02-19 20:17 UTC, caseyszilagyi approved these changes

2023-02-19 20:17 UTC, caseyszilagyi commented on backend/buybacks/views.py
> +    def update(self, request, *args, **kwargs):
Right now, anytime we hit a modify/create/delete endpoint, we just check for a 200/201/etc status to ensure it's successful and don't do anything with the response. So doesn't really matter what the response is. Just thought I'd let you know, but it's fine like this

2023-02-19 20:18 UTC, merged