[Front-End] Book Detail Detail View Refactor
ECE-458-Books/ece458books pull request #610
Opened 2023-03-18 04:41 UTC by nex-pixel

## Feature Description/Implementation
Fixed the detail view so viewing it shows normal text until the edit toggle is clicked upon which it will toggle to the editable fields method. Also refactored out a couple of components from the detail view.
## Dependencies

## Everything Else

2023-03-19 20:13 UTC, caseyszilagyi requested changes

2023-03-19 20:13 UTC, caseyszilagyi commented on frontend/src/components/text/BookDetailTextLabels.tsx
Any reason why this needs to be "BookDetailTextLabels" instead of "TextLabels"? There's not really a reason to have it in the components directory if it can't be used anywhere else

2023-03-19 20:13 UTC, caseyszilagyi commented on frontend/src/components/text/BookDetailToggleableNumberEditor.tsx
Same question as before. I'm also wondering what benefits this new component provides? I find the Props to be a little bit confusing. I'm not quite sure why we couldn't just use the NumberEditor/IntegerEditor/PriceEditor that we have been using up to this point

2023-03-20 00:49 UTC, nex-pixel commented on frontend/src/components/text/BookDetailTextLabels.tsx
not really. I think there are some specific things in it that are css that may need to be extracted to make it more general.

2023-03-20 00:56 UTC, nex-pixel commented on frontend/src/components/text/BookDetailToggleableNumberEditor.tsx
Hmm i was just trying to extract the triple duplicated input number format depending on output in the book detail, but I should try to utilize the number editor stuff instead.

2023-03-20 16:10 UTC, caseyszilagyi approved these changes

2023-03-20 16:10 UTC, merged