[BackEnd] Added remote books to books list, books initial add, books detail
ECE-458-Books/ece458books pull request #793
Opened 2023-04-08 01:42 UTC by hkder

## Feature Description/Implementation
Closes #769
Closes #770 
Closes #771 
Closes #772 

## Dependencies

## Everything Else

2023-04-08 14:05 UTC, caseyszilagyi requested changes

2023-04-08 14:05 UTC, caseyszilagyi commented on backend/books/views.py
> +        if remote_book_data:
What would happen here if remote_book exists for a given ISBN, but for some reason we can't get it from the external API (Google books)? Seems unlikely, but was just wondering

2023-04-09 01:30 UTC, danielfeinblatt commented
After Casey's questions have been addressed, LGTM

2023-04-10 14:13 UTC, hkder commented on backend/books/remote_books.py
> +        ret = ret[isbn]
this is related to parsing the response group 3 sends us. they send us an array not a dictionary.

2023-04-10 15:17 UTC, caseyszilagyi approved these changes
LGTM

2023-04-10 15:18 UTC, merged